name: Test My Golang Action

on:
  push:
    branches:
      - main

jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: Build and run the Golang Action
        run: |
          make build
          output=$(./setup-myapp)
          echo "Output: $output" >> output.txt

      - name: Print output
        run: |
          cat output.txt

      - name: Assert the output
        run: |
          expected="Output: terrahelp_0.7.5_linux_amd64.tar.gz is now available on PATH"
          output=$(cat output.txt)
          if [ "$output" != "$expected" ]; then
            echo "Assertion failed. Expected: $expected, Got: $output"
            exit 1
          fi
      - name: Assert the Download
        run: |
          ls -al "$GITHUB_WORKSPACE/bin"
          if [ ! -f "$GITHUB_WORKSPACE/bin/terrahelp_0.7.5_linux_amd64.tar.gz" ]; then
            echo "Assertion failed. File not found in bin"
            exit 1
          fi
      - name: Assert the binary output
        run: |
          echo "Path: $PATH"
          
          expected="terrahelp version 0.7.5"
          binary_output=$(terrahelp --version)
          if [ "binary_output" != "$expected" ]; then
            echo "Assertion failed. Expected: $expected, Got: $binary_output"
            exit 1
          fi
