name: Test My Golang Action

on:
  push:
    branches:
      - main

jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.6

      - name: Build and run the Golang Action
        run: |
          make build
          output=$(./setup-myapp)
          echo "Output: $output" >> output.txt

      - name: Print output
        run: |
          cat output.txt

      - name: Assert the output
        run: |
          expected="Output: my-binary-name is now available on PATH"
          output=$(cat output.txt)
          if [ "$output" != "$expected" ]; then
            echo "Assertion failed. Expected: $expected, Got: $output"
            exit 1
          fi
